export const labInputs = {
    trgol: [//L3
        { name: 'Sn', label: 'Sₙ (Puterea aparentă nominală) [VA]', type: 'number', value: 1000 },
        { name: 'U1n', label: 'U₁n (Tensiune primară nominală) [V]', type: 'number', value: 230 },
        { name: 'U2n', label: 'U₂n (Tensiune secundară nominală) [V]', type: 'number', value: 48 },
        { name: 'I1n', label: 'I₁n (Curent nominal primar) [A]', type: 'number', value: 0 },
        { name: 'I2n', label: 'I₂n (Curent nominal secundar) [A]', type: 'number', value: 0 },
        { name: 'U10', label: 'U₁₀ (Tensiune primară gol) [V]', type: 'number', value: 228.4 },
        { name: 'U20', label: 'U₂₀ (Tensiune secundară gol) [V]', type: 'number', value: 49.7 },
        { name: 'I10', label: 'I₁₀ (Curent gol) [A]', type: 'number', value: 0.4 },
        { name: 'P10', label: 'P₁₀ (Puterea la gol) [W]', type: 'number', value: 25.3 },
        { name: 'U1k', label: 'U₁k (Tensiune primară scurtcircuit) [V]', type: 'number', value: 7.35 },
        { name: 'I1k', label: 'I₁k (Curent scurtcircuit primar) [A]', type: 'number', value: 4.8 },
        { name: 'P1k', label: 'P₁k (Putere scurtcircuit) [W]', type: 'number', value: 33.3 },
        { name: 'I2K', label: 'I₂K (Curent scurtcircuit secundar) [A]', type: 'number', value: 22.2 },
    ],
    monofaz: [//L4
        { name: 'Sn', label: 'Sₙ (Puterea aparentă nominală) [kVA]', type: 'number', value: 1000 },
        { name: 'U1n', label: 'U₁n (Tensiune primară nominală) [V]', type: 'number', value: 230 },
        { name: 'U2n', label: 'U₂n (Tensiune secundară nominală) [V]', type: 'number', value: 48 },
        { name: 'I1n', label: 'I₁n (Curent nominal primar) [A]', type: 'number', value: 0 },
        { name: 'I2n', label: 'I₂n (Curent nominal secundar) [A]', type: 'number', value: 0 },
        { name: 'P1', label: 'P₁ (Puterea primar) [A]', type: 'text', value: [168, 177, 240, 334, 420] },
        { name: 'I1', label: 'I₁ (Curent primar) [A]', type: 'text', value: [0.8, 0.9, 1.1, 1.5, 1.9] },
        { name: 'I2', label: 'I₂ (Curent secundar) [A]', type: 'text', value: [3, 3.18, 4.48, 6.44, 8.2] },
        { name: 'U2', label: 'U₂ (Tensiune secundară) [V]', type: 'text', value: [48.1, 48, 47.9, 47.8, 47.7] },
        { name: 'U1', label: 'U₁ (Tensiune primară) [V]', type: 'number', value: 210},
        { name: 'cos ϕ2', label: 'cosϕ₂ (Factorul de putere secundar) [-]', type: 'number', value: 1 },
        { name: 'ƒ1', label: 'ƒ₁ (Frecvența) [Hz]', type: 'number', value: 50 },
    ],
    asincr: [//L7
        { name: 'Pn', label: 'Pₙ (Puterea nominală) [kW]', type: 'number', value: 3 },
        { name: 'Un', label: 'Uₙ (Tensiune nominală) [V]', type: 'number', value: 220 },
        { name: 'In', label: 'Iₙ (Curent nominal) [A]', type: 'number', value: 13.9 },
        { name: 'cos ϕn', label: 'cosϕₙ (Factorul de putere nominal) [-]', type: 'number', value: 0.69 },
        { name: 'ƒn', label: 'ƒₙ (Frecvența nominală) [Hz]', type: 'number', value: 50 },
        { name: 'nn', label: 'nₙ (Turația nominală) [rpm]', type: 'number', value: 920 },
        { name: 'n1', label: 'n₁ (Turația sincronă) [rpm]', type: 'number', value: 1000 },
        { name: 'PGn', label: 'P_Gₙ (Puterea generată nominală) [W]', type: 'number', value: 3400 },
        { name: 'UGn', label: 'U_Gₙ (Tensiune generată la ieșire) [V]', type: 'number', value: 170 },
        { name: 'IGn', label: 'I_Gₙ (Curent generat la ieșire) [A]', type: 'number', value: 20 },
        { name: 'Uen', label: 'Uₑₙ (Tensiune de excitație) [V]', type: 'number', value: 170 },
        { name: 'Ien', label: 'Iₑₙ (Curent de excitație) [A]', type: 'number', value: 0.7 },
        { name: 'nGn', label: 'n_Gₙ (Turația generatorului) [rpm]', type: 'number', value: 2500 },
        { name: 'U1', label: 'U₁ (Tensiune primară) [V]', type: 'text', value: [380, 380, 380, 380, 380, 380] },
        { name: 'I1', label: 'I₁ (Curent primar) [A]', type: 'text', value: [4.354, 4.357, 4.358, 4.359, 4.361, 4.367] },
        { name: 'P1', label: 'P₁ (Puterea primar) [W]', type: 'text', value: [145, 278, 291, 306, 324, 372] },
        { name: 'UG', label: 'U_G (Tensiune generată) [V]', type: 'text', value: [66, 49, 47, 45, 43, 37] },
        { name: 'IG', label: 'I_G (Curent generat) [A]', type: 'text', value: [0.7, 2.5, 2.7, 2.9, 3.1, 3.75] },
        { name: 'n', label: 'n (Turația) [rpm]', type: 'text', value: [929, 713, 691, 666, 637, 560] },
    ],
    sincr: [//L9
        { name: 'Sn', label: 'Sₙ (Puterea nominală) [kVA]', type: 'number', value: 3.7 },
        { name: 'Un', label: 'Uₙ (Tensiune nominală) [V]', type: 'number', value: 220 },
        { name: 'In', label: 'Iₙ (Curent nominal) [A]', type: 'number', value: 10 },
        { name: 'Uen', label: 'Uₑₙ (Tensiune de excitație) [V]', type: 'number', value: 0 },
        { name: 'Ien', label: 'Iₑₙ (Curent de excitație) [A]', type: 'number', value: 0.9 },
        { name: 'nn', label: 'nₙ (Turația nominală) [rpm]', type: 'number', value: 1500 },
        { name: 'U0', label: 'U₀ (Tensiune gol) [V]', type: 'text', value: [5.13, 89, 94, 98.6, 106, 113, 117.7, 123, 109.7] },
        { name: 'Ie', label: 'Iₑ (Curent gol) [A]', type: 'text', value: [0, 0.5, 0.55, 0.6, 0.65, 0.75, 0.8, 0.9, 0.7] },
        { name: 'Ie_sarc', label: 'Iₑ_sarc (Curent sarcină) [A]', type: 'number', value: 0.58 },
        { name: 'cos ϕ', label: 'cosϕ (Factorul de putere) [-]', type: 'number', value: 1 },
        { name: 'n', label: 'n (Turația) [rpm]', type: 'number', value: 750 },
        { name: 'U', label: 'U (Tensiune) [V]', type: 'text', value: [100, 94.76, 86.6, 81.5, 68.1, 60.4, 51] },
        { name: 'I', label: 'I (Curent) [A]', type: 'text', value: [0, 1.2, 2.24, 3.04, 3.81, 4.24, 4.8] },
    ]
};