export const labInputs = {
    trgol: [//L3
        { name: 'Sn', label: 'Puterea aparentă nominală (VA)', type: 'number', value: 1000 },
        { name: 'U1n', label: 'Tensiune primară nominală (V)', type: 'number', value: 230 },
        { name: 'U2n', label: 'Tensiune secundară nominală (V)', type: 'number', value: 48 },
        { name: 'I1n', label: 'Curent nominal primar (A)', type: 'number', value: 0 },
        { name: 'I2n', label: 'Curent nominal secundar (A)', type: 'number', value: 0 },
        { name: 'U10', label: 'Tensiune primară gol (V)', type: 'number', value: 228.4 },
        { name: 'U20', label: 'Tensiune secundară gol (V)', type: 'number', value: 49.7 },
        { name: 'I10', label: 'Curent gol (A)', type: 'number', value: 0.4 },
        { name: 'P10', label: 'Puterea la gol (W)', type: 'number', value: 25.3 },
        { name: 'U1k', label: 'Tensiune primară scurtcircuit (V)', type: 'number', value: 7.35 },
        { name: 'I1k', label: 'Curent scurtcircuit primar (A)', type: 'number', value: 4.8 },
        { name: 'P1k', label: 'Putere scurtcircuit (W)', type: 'number', value: 33.3 },
        { name: 'I2K', label: 'Curent scurtcircuit secundar (A)', type: 'number', value: 22.2 },
    ],
    monofaz: [//L4
        { name: 'Sn', label: 'Puterea aparentă nominală (kVA)', type: 'number', value: 1000 },
        { name: 'U1n', label: 'Tensiune primară nominală (V)', type: 'number', value: 230 },
        { name: 'U2n', label: 'Tensiune secundară nominală (V)', type: 'number', value: 48 },
        { name: 'I1n', label: 'Curent nominal primar (A)', type: 'number', value: 0 },
        { name: 'I2n', label: 'Curent nominal secundar (A)', type: 'number', value: 0 },
        { name: 'P1', label: 'Puterea primar (A)', type: 'text', value: [168, 177, 240, 334, 420] },
        { name: 'I1', label: 'Curent primar (A)', type: 'text', value: [0.8, 0.9, 1.1, 1.5, 1.9] },
        { name: 'I2', label: 'Curent secundar (A)', type: 'text', value: [3, 3.18, 4.48, 6.44, 8.2] },
        { name: 'U2', label: 'Tensiune secundară (V)', type: 'text', value: [48.1, 48, 47.9, 47.8, 47.7] },
    ],
    asincr: [//L7
        { name: 'Pn', label: 'Puterea nominala (kW)', type: 'number', value: 3 },
        { name: 'Un', label: 'Tensiune nominală (V)', type: 'number', value: 220 },
        { name: 'In', label: 'Curent nominal (A)', type: 'number', value: 13.9 },
        { name: 'cos ϕn', label: 'Factorul de putere nominal (-)', type: 'number', value: 0.69 },
        { name: 'ƒn', label: 'Frecvența nominală (Hz)', type: 'number', value: 50 },
        { name: 'nn', label: 'Turația nominală (rpm)', type: 'number', value: 920 },
        { name: 'PGn', label: 'Puterea generată nominală (kW)', type: 'number', value: 3.4 },
        { name: 'UGn', label: 'Tensiune generată la ieșire (V)', type: 'number', value: 170 },
        { name: 'IGn', label: 'Curent generat la ieșire (A)', type: 'number', value: 20 },
        { name: 'Uen', label: 'Tensiune de excitație (V)', type: 'number', value: 170 },
        { name: 'Ien', label: 'Curent de excitație (A)', type: 'number', value: 0.7 },
        { name: 'nGn', label: 'Turația generatorului (rpm)', type: 'number', value: 2500 },
        { name: 'U1', label: 'Tensiune primară (V)', type: 'text', value: [380, 380, 380, 380, 380, 380] },
        { name: 'I1', label: 'Curent primar (A)', type: 'text', value: [4.354, 4.357, 4.358, 4.359, 4.361, 4.367] },
        { name: 'P1', label: 'Puterea primar (W)', type: 'text', value: [145, 278, 291, 306, 324, 372] },
        { name: 'UG', label: 'Tensiune primară (V)', type: 'text', value: [66, 49, 47, 45, 43, 37] },
        { name: 'IG', label: 'Curent primar (A)', type: 'text', value: [0.7, 2.5, 2.7, 2.9, 3.1, 3.75] },
        { name: 'n', label: 'turația (rpm)', type: 'text', value: [929, 713, 691, 666, 637, 560] },
    ],
    sincr: [//L9
        { name: 'Sn', label: 'Puterea aparentă nominală (kVA)', type: 'number', value: 3.7 },
        { name: 'Un', label: 'Tensiune nominală (V)', type: 'number', value: 220 },
        { name: 'In', label: 'Curent nominal (A)', type: 'number', value: 10 },
        { name: 'Uen', label: 'Tensiune de excitație (V)', type: 'number', value: 0 },
        { name: 'Ien', label: 'Curent de excitație (A)', type: 'number', value: 0.9 },
        { name: 'nn', label: 'Turația nominală (rpm)', type: 'number', value: 1500 },
        { name: 'U0', label: 'Tensiune gol (V)', type: 'text', value: [5.13, 89, 94, 98.6, 106, 113, 117.7, 123, 109.7] },
        { name: 'Ie', label: 'Curent gol (A)', type: 'text', value: [0, 0.5, 0.55, 0.6, 0.65, 0.75, 0.8, 0.9, 0.7] },
        { name: 'Ie_sarc', label: 'Curent sarcina Ie(A)', type: 'number', value: 0.58 },
        { name: 'cos ϕ', label: 'Factorul de putere (-)', type: 'number', value: 1 },
        { name: 'n', label: 'Turația sarcina n(rpm)', type: 'number', value: 750 },
        { name: 'U', label: 'Tensiune (V)', type: 'text', value: [100, 94.76, 86.6, 81.5, 68.1, 60.4, 51] },
        { name: 'I', label: 'Curent (A)', type: 'text', value: [0, 1.2, 2.24, 3.04, 3.81, 4.24, 4.8] },
    ]
};