export const labInputs = {
    trgol: [//L3
        { name: 'Sn', label: 'Puterea aparentă nominală (kVA)', type: 'number' },
        { name: 'U1n', label: 'Tensiune primară nominală (V)', type: 'number' },
        { name: 'U2n', label: 'Tensiune secundară nominală (V)', type: 'number' },
        { name: 'I1n', label: 'Curent nominal primar (A)', type: 'number' },
        { name: 'I2n', label: 'Curent nominal secundar (A)', ype: 'number' },
        { name: 'U10', label: 'Tensiune primară gol (V)', type: 'number' },
        { name: 'U20', label: 'Tensiune secundară gol (V)', type: 'number' },
        { name: 'I10', label: 'Curent gol (A)', type: 'number' },
        { name: 'P10', label: 'Puterea la gol (W)', ype: 'number' },
        { name: 'U1k', label: 'Tensiune primară gol (V)', type: 'number' },
        { name: 'I1k', label: 'Curent scurtcircuit primar (A)', type: 'number' },
        { name: 'P1k', label: 'Putere scurtcircuit (W)', type: 'number' },
        { name: 'I2K', label: 'Curent scurtcircuit secundar (A)', type: 'number' },
    ],
    monofaz: [//L4
        { name: 'Sn', label: 'Puterea aparentă nominală (kVA)', type: 'number' },
        { name: 'U1n', label: 'Tensiune primară nominală (V)', type: 'number' },
        { name: 'U2n', label: 'Tensiune secundară nominală (V)', type: 'number' },
        { name: 'I1n', label: 'Curent nominal primar (A)', type: 'number' },
        { name: 'I2n', label: 'Curent nominal secundar (A)', type: 'number' },
        { name: 'P1', label: 'Puterea primar (A)', type: 'number' },
        { name: 'I1', label: 'Curent primar (A)', type: 'number' },
        { name: 'I2', label: 'Curent secundar (A)', type: 'number' },
        { name: 'U2', label: 'Tensiune secundară (V)', type: 'number' },
      ],
    asincr: [//L7
        { name: 'Pn', label: 'Puterea nominala (kW)', type: 'number' },
        { name: 'Un', label: 'Tensiune nominală (V)', type: 'number' },
        { name: 'In',   label: 'Curent nominal (A)', type: 'number' },
        { name: 'cos ϕn', label: 'Factorul de putere nominal (-)', type: 'number' },
        { name: 'ƒn', label: 'Frecvența nominală (Hz)', type: 'number' },
        { name: 'nn', label: 'Turația nominală (rpm)', type: 'number' },
        { name: 'PGn', label: 'Puterea generată nominală (kW)', type: 'number' },
        { name: 'UGn', label: 'Tensiune generată la ieșire (V)', type: 'number' },
        { name: 'IGn',   label: 'Curent generat la ieșire (A)', type: 'number' },
        { name: 'Uen', label: 'Tensiune de excitație (V)', type: 'number' },
        { name: 'Ien',   label: 'Curent de excitație (A)', type: 'number' },
        { name: 'nGn', label: 'Turația generatorului (rpm)', type: 'number' },
        { name: 'U1', label: 'Tensiune primară (V)', type: 'number' },
        { name: 'I1', label: 'Curent primar (A)', type: 'number' },
        { name: 'P1', label: 'Puterea primar (W)', type: 'number' },
        { name: 'UG', label: 'Tensiune primară (V)', type: 'number' },
        { name: 'IG', label: 'Curent primar (A)', type: 'number' },
        { name: 'n', label: 'turația (rpm)', type: 'number' },
    ],   
    sincr: [//L9
        { name: 'Sn', label: 'Puterea aparentă nominală (kVA)', type: 'number' },
        { name: 'Un', label: 'Tensiune nominală (V)', type: 'number' },
        { name: 'In',   label: 'Curent nominal (A)', type: 'number' },
        { name: 'Uen', label: 'Tensiune de excitație (V)', type: 'number' },
        { name: 'Ien',   label: 'Curent de excitație (A)', type: 'number' },
        { name: 'nn', label: 'Turația nominală (rpm)', type: 'number' },
        { name: 'U0', label: 'Tensiune gol (V)', type: 'number' },
        { name: 'Ie', label: 'Curent gol (A)', type: 'number' },
        { name: 'cos ϕ', label: 'Factorul de putere (-)', type: 'number' },
        { name: 'U', label: 'Tensiune (V)', type: 'number' },
        { name: 'I', label: 'Curent (A)', type: 'number' },
    ]
  };